Dev
seanyasno/ghostrelor pull request #1
Opened 2020-04-20 17:25 UTC by seanyasno

Finished part A

2020-04-20 17:34 UTC, ETHANTALJAFFE commented on src/index.js
> +let todoDatabase = new TodoDatabase(updateTodosView);
use `const` instead of `let` to indicate that the variable does not change

2020-04-20 18:17 UTC, jafold requested changes
Make sure to fix issues throughout the PR. I might have not mentioned the mistake every time it happened. Once should be enough.

Overall pretty cool, good work :)

2020-04-20 18:17 UTC, jafold commented on src/index.js
> +    if (event.keyCode === 13) {
create `CONST ENTER_KEY_CODE = 13`

2020-04-20 18:17 UTC, jafold commented on src/index.js
> +let todoDatabase = new TodoDatabase(updateTodosView);
use `const` instead of `let` to indicate that the variable does not change

2020-04-20 18:17 UTC, jafold commented on src/index.js
> +import {TodoDatabase, updateTodosView, addTodo, initTodoView} from "./models/index.js";
use single quotes for imports

2020-04-20 18:17 UTC, jafold commented on src/models/addTodo.js
> +  let description = document.getElementById('todo-input').value;
`const`

2020-04-20 18:17 UTC, jafold commented on src/models/addTodo.js
> +    let todoItem = new TodoItem(description);
`const`

2020-04-20 18:17 UTC, jafold commented on src/models/TodoItem.js
> +  constructor(description='', done=false) {
spacing after `=`

2020-04-20 18:17 UTC, jafold commented on src/models/TodoDatabase.js
> +  }
why do you use args? You're always passing the `TodoItemView` as 2nd parameter. This ambiguity does not seem necessary and makes it tougher to understand your code flow

2020-04-20 18:17 UTC, ETHANTALJAFFE commented on src/models/todo-actions/index.js
> +}
Move module out of the /models directory

2020-04-20 18:17 UTC, ETHANTALJAFFE commented on src/models/todo-actions/todoAction.js
> +    let todoId = todosElements[i].id.split('-')[2];
`const`

2020-04-20 18:17 UTC, ETHANTALJAFFE commented on src/models/todo-actions/todoAction.js
> +export default function todoAction(effect, elementId) {
I don't know if `effect` is the best name. Maybe `callback`?

2020-04-21 09:43 UTC, jafold requested changes
One thing: project structure is still not good enough. Modules doesn't make sense. You're updating views and changing states. What does that have to do with `modules`?

2020-04-21 10:57 UTC, ETHANTALJAFFE commented on src/modules/todo-actions/todoAction.js
> +export default function todoAction(effect, elementId) {
Change to `addEventListenerToItem`

2020-04-21 11:16 UTC, jafold approved these changes
Fix issues in next PR

2020-04-21 11:16 UTC, jafold commented on src/modules/todo-actions/todoAction.js
> +  }
Change to `addEventListenerToItem`

2020-04-21 11:16 UTC, jafold commented on src/modules/todo-actions/todoAction.js
> +export default function todoAction(effect, elementId) {
Change `effect` to `callback`

2020-04-21 11:16 UTC, ETHANTALJAFFE commented on src/modules/todo-actions/checkTodo.js
> +}
rename it `addCheckEventToItem`

2020-04-21 11:16 UTC, ETHANTALJAFFE commented on src/modules/todo-actions/removeTodo.js
> +export default function removeTodo(todoDatabase) {
rename it `addRemoveEventToItem`

2020-04-21 11:16 UTC, merged